use-platform/use-platform

src/semantic/calendar/__examples__/default.tsx, src/semantic/calendar/__examples__/index.examples.ts, src/semantic/calendar/index.ts, src/semantic/calendar/readme.md, src/semantic/calendar/types.ts, src/semantic/calendar/useCalendarCell.ts, src/shared/types/calendar.ts, src/shared/types/common.ts, src/shared/types/index.ts
Что сделал:
- Перенес хук `useCalendarCell`
- Описал большую часть типов
=> feat(calendar): implement useCalendarCell hook

src/semantic/checkbox/useCheckbox.ts, src/semantic/toggle/useToggle.ts
=> Femove ref generic

src/interactions/press/types.ts, src/interactions/press/usePress.ts, src/interactions/press/utils/create-press-event.ts, src/libs/i18n/LocaleProvider.tsx, src/libs/i18n/index.ts, src/semantic/button/useButton.ts, src/shared/types/button.ts, tsconfig.prod.json
- Поменял в `tsconfig.json` свойство `jsx` с `react-jsx` на `react`, чтобы работало на 16 реакте
- Улучшил типы для `usePress` и `useButton`
- Сделал реэкспорт `LocaleProvider` из `i18n`
=> Few small fixes

src/interactions/press/usePress.test.tsx, src/interactions/press/usePress.ts, src/interactions/press/utils/create-press-event.ts, src/shared/types/events.ts
=> Support currentTarget property in press event

src/index.ts, src/interactions/focus/__examples__/default.tsx, src/interactions/focus/__examples__/focus-within.tsx, src/interactions/focus/__examples__/focus.tsx, src/interactions/focus/__examples__/index.examples.ts, src/interactions/focus/index.ts, src/interactions/focus/useFocus.test.tsx, src/interactions/focus/useFocus.ts, src/interactions/focus/useFocusWithin.test.tsx, src/interactions/focus/useFocusWithin.ts
DEMO: https://deploy-preview-60--web-platform.netlify.app/?path=/story/interactions-focus--default или https://611e6c228305bd000797b265--web-platform.netlify.app/?path=/story/interactions-focus--focus
=> Implement useFocus and useFocusWithin hooks

package.json, src/libs/utils/number.ts, src/semantic/datetimefield/__examples__/default.tsx, src/semantic/datetimefield/constants.ts, src/semantic/datetimefield/types.ts, src/semantic/datetimefield/useDateTimeField.test.tsx, src/semantic/datetimefield/useDateTimeFieldSegment.ts, src/semantic/datetimefield/useDateTimeFieldState.test.tsx, src/semantic/datetimefield/useDateTimeFieldState.ts, src/semantic/datetimefield/utils/DateComponents.ts, src/semantic/datetimefield/utils/DateTimeFieldAdapter.ts, src/semantic/datetimefield/utils/segment.ts
Demo: https://deploy-preview-62--web-platform.netlify.app/?path=/story/semantic-datetimefield--default
=> Improve useDateTimeFieldState hook

.github/workflows/docs.yml
Cделал публикацию preview и latest версий в github pages.
=> Setup deploy to gh-plages

src/semantic/radio/__examples__/default.tsx, src/semantic/radio/__examples__/grouped.tsx, src/semantic/radio/__examples__/standalone.tsx, src/semantic/radio/useRadio.test.tsx, src/semantic/radio/useRadio.ts, src/semantic/radio/useRadioGroup.test.tsx, src/semantic/radio/useRadioGroup.ts, src/semantic/radio/useRadioGroupState.test.tsx, src/semantic/radio/useRadioGroupState.ts
1. Запустил prettier с обновленным конфигом
2. Сделал небольшой рефакторинг кода
=> Fix code-style

src/index.ts, src/libs/merge-props/merge-props.test.ts, src/libs/merge-props/merge-props.ts, src/semantic/label/__examples__/default.tsx, src/semantic/label/__examples__/index.examples.tsx, src/semantic/label/__examples__/multipleLabels.tsx, src/semantic/label/index.ts, src/semantic/label/types.ts, src/semantic/label/useLabel.test.tsx, src/semantic/label/useLabel.ts
=> feat(label): impl useLabel

.eslintrc.js, src/semantic/datetimefield/useDateTimeFieldState.test.tsx, src/semantic/radio/useRadioGroup.test.tsx
=> chore: added new rule for brank line before return in linter

.gitignore
=> chore: added vscode configs folder to gitignore

package.json
Добавил `quiet` флаг для сборки сторибука, чтобы в CI не засорять логи.
=> Add silent mode for storybook build

src/semantic/calendar/__examples__/default.tsx, src/semantic/calendar/types.ts, src/semantic/calendar/useRangeCalendarState.test.tsx, src/semantic/calendar/useRangeCalendarState.ts, src/semantic/calendar/useSingleCalendarState.ts, src/semantic/calendar/utils/common.ts, src/semantic/datepicker/types.ts, src/semantic/datepicker/useDatePicker.ts, src/semantic/datepicker/useDatePickerState.ts, src/semantic/datepicker/utils.ts, src/semantic/datetimefield/__examples__/default.tsx, src/semantic/datetimefield/useDateTimeField.test.tsx, src/semantic/datetimefield/useDateTimeFieldState.test.tsx, src/semantic/datetimefield/useDateTimeFieldState.ts, src/semantic/datetimefield/utils/DateComponents.ts, src/semantic/datetimefield/utils/DateTimeFieldAdapter.ts, src/semantic/datetimefield/utils/format.ts, src/shared/types/common.ts, src/shared/types/input.ts
- поправил типы
- сделал триггер `onChange` при выборе даты начала
=> Trigger onChange when select start date

src/semantic/datepicker/useDateRangePickerState.test.ts, src/semantic/datepicker/useDateRangePickerState.ts
После фикса #106 DatePicker стал закрываться после первого выбора. Это ПР чинит это поведение
=> Close datepicker if set start and end

src/libs/collections/CacheableList.test.ts, src/libs/collections/CacheableList.ts, src/libs/collections/CollectionBuilder.test.tsx, src/libs/collections/CollectionBuilder.ts, src/libs/collections/index.ts, src/libs/collections/types.ts, src/libs/collections/utils.ts, tsconfig.json
Накидал прототип коллекций. По сути это упрощенная адобовская реализация. Это ядро, которое превращает `jsx` в абстрактную структуру. Хочется это обсудить, так как по мне пользоваться этим с одной стороны удобно, но есть некоторые нюансы
=> Implement collection builder

src/semantic/datetimefield/useDateTimeField.test.tsx, src/semantic/datetimefield/useDateTimeFieldSegment.ts
=> Prevent keydown event with enter key

package-lock.json, package.json, src/index.ts, src/libs/virtual-scroll/VirtualCollection.test.tsx, src/libs/virtual-scroll/VirtualCollection.tsx, src/libs/virtual-scroll/__examples__/default.tsx, src/libs/virtual-scroll/__examples__/index.examples.tsx, src/libs/virtual-scroll/__examples__/virtualiztionComponent.tsx, src/libs/virtual-scroll/index.ts, src/libs/virtual-scroll/types.ts, src/libs/virtual-scroll/useVirtualized.test.tsx, src/libs/virtual-scroll/useVirtualized.tsx
=> feat(label): impl virtualization

src/interactions/press/usePress.ts, src/interactions/press/utils/text-selection.ts, src/semantic/button/useButton.test.tsx, src/semantic/button/useButton.ts
Resolve #25 
1. Подрефакторил название переменной `pressStarted` -> `isPressStarted`
2. Удалил press-обработчики с dom-узла и написал тест
=> Omit extra props from dom

src/semantic/textfield/__examples__/password.tsx, src/semantic/textfield/__examples__/simple.tsx, src/semantic/textfield/__examples__/textarea.tsx, src/semantic/textfield/useClearButton.ts, src/semantic/textfield/useTextField.ts
Сделал более точный вывод типов в зависимости от установленной ссылки на элемент.
=> Return correct type from useTextfield

src/index.ts, src/interactions/outside-click/__examples__/default.tsx, src/interactions/outside-click/__examples__/index.examples.tsx, src/interactions/outside-click/index.ts, src/interactions/outside-click/types.ts, src/interactions/outside-click/useOutsideClick.test.tsx, src/interactions/outside-click/useOutsideClick.ts
=> feat(click outside): implement click outside hook

src/semantic/textfield/useTextField.ssr.test.tsx, src/semantic/textfield/useTextField.ts
=> Use useIsomorphicLayoutEffect instead useLayoutEffect

src/semantic/button/__examples__/default.tsx, src/semantic/button/useButton.ts, src/semantic/spinbutton/__examples__/default.tsx, src/semantic/textfield/__examples__/simple.tsx, src/semantic/textfield/useAutoResize.test.tsx, src/semantic/textfield/useTextField.test.tsx, src/semantic/textfield/useTextField.ts
=> Remove ElementType interface

.storybook/main.js, CODESTYLE.md, LICENSE, src/interactions/focus/__examples__/default.tsx, src/interactions/focus/__examples__/focus-within.tsx, src/interactions/focus/__examples__/focus.tsx, src/interactions/hover/__examples__/default.tsx, src/interactions/keyboard-event/__examples__/default.tsx, src/interactions/outside-click/__examples__/default.tsx, src/interactions/press/__examples__/default.tsx, src/libs/virtual-scroll/__examples__/default.tsx, src/libs/virtual-scroll/__examples__/virtualiztionComponent.tsx, src/semantic/button/__examples__/default.tsx, src/semantic/calendar/__examples__/default.tsx, src/semantic/checkbox/__examples__/default.tsx, src/semantic/datetimefield/__examples__/default.tsx, src/semantic/label/__examples__/default.tsx, src/semantic/label/__examples__/multipleLabels.tsx, src/semantic/label/types.ts, src/semantic/overlay/__examples__/default.tsx, src/semantic/radio/__examples__/default.tsx, src/semantic/radio/__examples__/grouped.tsx, src/semantic/radio/__examples__/standalone.tsx, src/semantic/spinbutton/__examples__/default.tsx, src/semantic/switch/__examples__/default.tsx, src/semantic/textfield/__examples__/password.tsx, src/semantic/textfield/__examples__/simple.tsx, src/semantic/textfield/__examples__/textarea.tsx, tsconfig.json
=> Use new alias @use-platform/react

src/semantic/textfield/__examples__/password.tsx
1. Change component name for password example PasswordTextField -> PasswordField
2. Remove unused args
=> Refactor password example

src/interactions/hover/useHover.test.ts, src/interactions/hover/useHover.ts
=> Fixed useHover for touch devices

src/semantic/visually-hidden/VisuallyHidden.test.tsx, src/semantic/visually-hidden/VisuallyHidden.tsx, src/semantic/visually-hidden/__snapshots__/VisuallyHidden.test.tsx.snap
=> feat: add VisuallyHidden component

package.json
=> fix: fix treeshaking

.github/workflows/ci.yml, src/semantic/radio/useRadio.ts, src/semantic/radio/useRadioGroup.ts
=> refactor: refactor remove redundant props
